name: PrisonSystem
version: 1.0.0B
api: [3.0.0]
main: Raphael\Prison\Blaze
author: Raphael S.
commands:
    prender:
        description: Prenda um Jogador!

# Feito por Raphael S. 
# Discord: https://www.blazehosting.com.br/discord
# https://github.com/Raphael1S/Prison-System
